name: Deploy to Production

on:
  push:
    branches:
      - deploys

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "holiday-games"
          heroku_email: "alexandraroseingram@gmail.com"
